#!/bin/sh
# test
DATA=~/Documents/brainlog.txt

while getopts el opt
do
  case $opt in 
  e) gnome-terminal -e "vi ${DATA}";exit 0;;
  l) cat $DATA;exit 0;;
  esac
done


echo $* >> ~/Documents/brainlog.txt;

